Post a review
royr5/gatefold-frontend pull request #15
Opened 2024-01-08 20:32 UTC by royr5

- Modified the placeholder text.
- Optimistically render reviews after a successful review post.
- Add form validation

2024-01-08 22:00 UTC, ari-abendstern requested changes
Your code is gorgeous and so readable and so much better than I could have done - I think we just need to change the validation so that it lets people post without body/title

2024-01-08 22:00 UTC, ari-abendstern commented on components/ReviewModal.tsx
> +      if (!body) errorMessage += "\n- Body";
Weren't title and body going to be optional? So that people could just rate if they want?

2024-01-08 22:00 UTC, ari-abendstern commented on components/ReviewModal.tsx
> +        });
I'm stealing this next time I need to optimistically render something and can't be bothered to type and there's nothing you can do about it

2024-01-09 09:29 UTC, ari-abendstern approved these changes
<3

2024-01-09 09:51 UTC, Jord000 approved these changes

2024-01-09 09:51 UTC, merged